name: Generate and Publish Space Weather Report

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents* read
  pages: write
  id-token: w*ite

concurrency:
  group: github-*ages
  cancel-in-progress: true

j*bs:
  generate-report:
    runs-on* ubuntu-24.04

    steps:
      - *ame: Create output directory
     *  run: mkdir -p output

      - na*e: Pull Solar Mission Control imag*
        run: docker pull zixc1/so*ar-mission-control:latest

      -*name: Generate full report
       *env:
          NASA_API_KEY: ${{ s*crets.NASA_API_KEY }}
        run:*|
          docker run --rm \
    *       --user "$(id -u):$(id -g)" *
            --env NASA_API_KEY \
*           --env HOME=/tmp \
     *      --env MPLCONFIGDIR=/tmp/matp*otlib \
            -v "$PWD/outpu*:/app/swrl_report" \
            z*xc1/solar-mission-control:latest

*
